@CafeSanchez.API_HostAddress = http://localhost:5148/api
@Client_Authorization_Key = E888F6C3-7720-4938-A6C5-B79C126D1FA3

GET {{CafeSanchez.API_HostAddress}}/products
Client-Authorization-Key: {{Client_Authorization_Key}}
Accept: application/json

###
GET {{CafeSanchez.API_HostAddress}}/orders
Client-Authorization-Key: {{Client_Authorization_Key}}
Accept: application/json

###
POST {{CafeSanchez.API_HostAddress}}/orders
Client-Authorization-Key: {{Client_Authorization_Key}}
Accept: application/json
Content-Type: application/json

{
  "customerName": "TestCustomer",
  "discount": 0, 
  "items": [
    { "id": "6d5f461d-45dc-495b-9ace-c7d16c6f5621", "quantity": 2 }, 
    { "id": "929e4c46-b7f6-4782-ba09-424a1df5d581", "quantity": 1}
  ]
}